apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- sealed-secret.yaml
- deployment.yaml
- service.yaml
- service-external.yaml

images:
- name: backstage
  newName: brucorreia/backstage
  newTag: 1.0.8
