apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: evolutionapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 10
            preference:
              matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - node01
          - weight: 100
            preference:
              matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - node02
          - weight: 50
            preference:
              matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - node03
          - weight: 30
            preference:
              matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - node04
      containers:
      - name: postgres
        image: postgres:latest
        ports:
        - containerPort: 5432
        env:
        - name: DATABASE_ENABLED
          value: "true"
        - name: DATABASE_PROVIDER
          value: "postgresql"
        - name: DATABASE_CONNECTION_CLIENT_NAME
          value: "evolution_exchange"        
        - name: DATABASE_SAVE_DATA_INSTANCE
          value: "true"  
        - name: DATABASE_SAVE_DATA_NEW_MESSAGE
          value: "true"  
        - name: DATABASE_SAVE_MESSAGE_UPDATE
          value: "true"
        - name: DATABASE_SAVE_DATA_CONTACTS
          value: "true"
        - name: DATABASE_SAVE_DATA_CHATS
          value: "true"
        - name: DATABASE_SAVE_DATA_LABELS
          value: "true"
        - name: DATABASE_SAVE_DATA_HISTORIC
          value: "true"
        - name: CACHE_REDIS_ENABLED
          value: "false"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: DB_PASSWORD
        - name: DATABASE_CONNECTION_URI
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: DATABASE_CONNECTION_URI        
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgres-storage
      volumes:
      - name: postgres-storage
        hostPath:
          path: /mnt/storage/postgres-data
          type: DirectoryOrCreate