apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronjob
  namespace: news
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: news
            image: news
            envFrom:
              - secretRef:
                  name: news-secrets
          restartPolicy: OnFailure
