apiVersion: batch/v1
kind: CronJob
metadata:
  name: my-cronjob
spec:
  schedule: "*/2 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: news
            namespace: news
            image: news
            envFrom:
              - secretRef:
                  name: news-secrets
          restartPolicy: OnFailure
