apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- cronjob.yaml
- sealed-secret.yaml
- namespace.yaml

images:
- name: news
  newName: brucorreia/news
  newTag: 5225fe751ad41a60694078b77ed8a02eed4d0833
