---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-assistant
  namespace: home-assistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: home-assistant
  template:
    metadata:
      labels:
        app: home-assistant
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            preference:
              matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - node01
          - weight: 50
            preference:
              matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - node02
          - weight: 30
            preference:
              matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - node03
          - weight: 10
            preference:
              matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - node04
      containers:
      - name: home-assistant
        image: homeassistant/home-assistant:latest
        command: ["sh", "-c"]
        args:
          - |
            pip install pytapo
            python3 -m homeassistant --config /config
        env:
          - name: DB_URL
            value: "mysql://homeassistant:$(DB_PASSWORD)@mariadb:3306/homeassistant"
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: home-assistant-secret
                key: DB_PASSWORD
        volumeMounts:
          - name: home-assistant-config
            mountPath: /config
      volumes:
        - name: home-assistant-config
          hostPath:
            path: /mnt/storage/home-assistant-config
      restartPolicy: Always
