---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-assistant
  namespace: home-assistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: home-assistant
  template:
    metadata:
      labels:
        app: home-assistant
    spec:
      containers:
      - name: home-assistant
        image: homeassistant/home-assistant:latest
        env:
          - name: DB_URL
            value: "mysql://homeassistant:$(DB_PASSWORD)@mariadb:3306/homeassistant"
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: home-assistant-secret
                key: DB_PASSWORD
        volumeMounts:
          - name: home-assistant-config
            mountPath: /config/configuration.yaml
            subPath: configuration.yaml
      volumes:
        - name: home-assistant-config
          configMap:
            name: home-assistant-config 
      restartPolicy: Always