apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
  namespace: home-assistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            preference:
              matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - node01
          - weight: 50
            preference:
              matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - node02
          - weight: 30
            preference:
              matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - node03
          - weight: 10
            preference:
              matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - node04       
      containers:
      - name: mariadb
        image: mariadb:latest
        envFrom:
          - secretRef:
              name: mariadb-secret
        ports:
          - containerPort: 3306
        volumeMounts:
          - name: mariadb-storage
            mountPath: /var/lib/mysql
      volumes:
        - name: mariadb-storage
          hostPath:
            path: /mnt/storage/mariadb-home-assistant
