---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mariadb-secret
  namespace: mariadb
spec:
  encryptedData:
    ROOT_PASSWORD: AgBjkaPGYDqTyM2dXIfYXrogBp1+GN1ZBT8QdCepxbHJ9vq50e3290Le2huxN+uRfehBYSkPhya96SFMYuIlmGiLLxvhB5W7qLwRa59vX918XHRgONSKnwToiAKweH+0tP+s05SRZ+noE3cjkIMBQYGIdXuThr791dUFsmWY/HUAcNnUJjBTv60ho4LpnWLD8/8dovBX6sM4T2dEC3X0qKqvj6jVpRfb3yT4G1uTg9750aBTWba1t6xll9+seQcG0A8HVrON1sCMTQTEU9QHXOecmkkAhxvhdxHnP2Oy1v5ZE7XNa/WxmZNo41T8VIDq3UQIFHJgIQQhmm7IO7ZacfgkNQYVcXR5siaqgFZhIQetqSMDHkNdxRyJmfJwJMdxv0c8u0sxBbQiH/MaMwfBLCj7TqfpnGgCELPfMdVdwd1xCOt7dKecyAOkUvZcVGlvF3K3TsMJsTDma/XZ+QiA1ECsMcrWxriOwe1nvMdreswe1wQM9V9JlMftBj2F0fg3u572W8VkU6zFNBx3TRtiayJzYdjBROX++w6o/FCJ9/lOCnZAl06jKrbKriBec3ZQbTMVsYqWAM/TWt0e2iC8va5vP1sr8usKjgt8f+R0oGKlM5JeuwAbqDgbqBAELy+kPKRLtRYBDHMtGAyqT7RzeegRsNZIlb/sfaqyceyZoRYP3+BK+QfvbgIKHcHp+QvcFKA/LxTzSwkK3Qi6b8Rjyvy7NR0X9wMMha+2
    USER_PASSWORD: AgA32c8vJWVL9cHYEYuXss2h4XGuCVlhhNjiIhjKQaR6ajbZhrxQamodxc6gRRFlJUnuNf+DQ2KO6WH3IG3RZF4bEem+MTUceoH4M4bu9Fa8BRx+CAgeb221vqR8PPiBe9zlkfWSvvBJXqhupFnqXlqreatMxIbJtDQeOSEbSReSWdQYBCHWRltLD1jkciDzLZ5Z+1CrcaxkUE7XLjTrtUonwYkMBLty+KlsKxVIYfmK8IID8bLHKrDcnUGspMptk2KytCi+j8Z0CCW6gJRZc9dJTNxkvturQ9Igyvk+FXADAf1A1YkzewK/jLkn+vQdIlVJLVIkDZ50yyfPT+j8fvWFrV0Q9a0Ojf+nAnT0fHopYKnTlnWA71mcQIEWNykt+8NRTGCNJMAxv6y1r3TSPUTNGeNy9JHTw9IvZTfQTHjer8rK3H/jiUea3lOWSdTsWBJM4pItmS4MTAlkAwk72aSjPSwvfWo5KqIdpZYPpAO5MzIUwFk0f22EdNu+DhbWS/Nz7fvVkvCC0PngCrsrlkqfDwfJ2K7TKlWi5zNtY/bM3VTfnuMQlDJYgbA9kSwZTBori3x4XdbZO76dsv86OUpKAYb00DufO/mi+xZiYtqk6oXOjDeOWK02+DBzPU20ildgwb4HHJJiQDfaVNbliY6OuS2Nhfk4xScDMIv46R+l6Bvagk8XFjFAthH12y0xtLdQxYHx5qXIaBBnHds4A19SfF9FlKSl9/O5
  template:
    metadata:
      creationTimestamp: null
      name: mariadb-secret
      namespace: mariadb
    type: Opaque
