---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mariadb-secret
  namespace: mariadb
spec:
  encryptedData:
    ROOT_PASSWORD: AgAoT1YLWXgFpgkgF5YU0As23W5IB0QmbjO26IEHYLoUSAqEyLTPBmBvKs6g4vWR7vgBU2004HiL2aNZViSi4ln4L8VTbY/T+JHbz7NXjoekw8ICwMtktuvIj+/rUQ/0dqo/a+5kzBn5v0wn1HD4olGOfi9oOJ/LXRp6A5tgkVWcqaXQP59cDaZNybXJT2POZuxr9nLemHEzqSjU7PU6q010giHSoc1kn7pchsAI7fIyK/PLA3zgaN3+r1zKw7ohUL7pFOotgHVoiYTN+9+xBNsRJXTwydL4DTdqqSUV6YPBeO8dAn+ihRLGHDz2/Lk0eSuaBIsAV3Iu5Tg8j50waTzFLy76/RNzSX7q9AuzORNdR1B368Daq+PUpaSpdEEX88vCCG7wVPdQL8pC2+Dban/qfi2lRXZFcoDa2UiufTwCi7KM9ywIb6iz4P97eU6ff3Lyhis+Bt9zU026we7Dq4b3RyadSkXp5+6O39Rfy8pdAZ1B873BPjo8qfg1MAjSHYb+4Hxn0PKYDK+nyOcIfw9bd02/dSjO0XnwRzzBVJ5dl4M8bBCCrJPst/Ji7wrgLq8ZtaCD9Z9ftSKoJt2O9XTNSfGl/IWw0an8PGywYvIAhgA8zJjZhaNcky2M4IbT3gKd8nyuFFem185aTNrECo6k8wee4NHW6eT5tu0bYtYx53+rzb5V61lDtdvqNmcuFAaL3CXo0PGmzFxOlxPoY++GldnqKwjQevSj
  template:
    metadata:
      creationTimestamp: null
      name: mariadb-secret
      namespace: mariadb
    type: Opaque
