apiVersion: v1
kind: Service
metadata:
  name: unifi-server-service
  namespace: unifi
spec:
  ports:
  - name: http-port
    nodePort: 30080
    port: 8080
    targetPort: 8080
  - name: https-port
    nodePort: 30443
    port: 8443
    targetPort: 8443
  - name: stun-port
    nodePort: 30378
    port: 3478
    targetPort: 3478
  selector:
    app: unifi
  type: NodePort