apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft
  namespace: minecraft
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: minecraft
  template:
    metadata:
      labels:
        app: minecraft
    spec:
      containers:
      - name: minecraft
        image: itzg/minecraft-server:latest
        ports:
        - containerPort: 25565
          name: game
          protocol: TCP
        env:
        - name: EULA
          value: "TRUE"
        - name: VERSION
          value: "1.20.1"
        - name: TYPE
          value: "PAPER"
        - name: MEMORY
          value: "2G"
        - name: MAX_PLAYERS
          value: "5"
        - name: ONLINE_MODE
          value: "FALSE" # permite login sem conta Mojang
        - name: ENABLE_RCON
          value: "false"
        volumeMounts:
        - name: mc-data
          mountPath: /data
        resources:
          requests:
            memory: "1536Mi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
      volumes:
      - name: mc-data
        persistentVolumeClaim:
          claimName: mc-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mc-data
  namespace: minecraft
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: longhorn

