apiVersion: v1
kind: Service
metadata:
  name: minecraft
  namespace: minecraft
spec:
  selector:
    app: minecraft
  ports:
  - name: game
    port: 25565
    targetPort: 25565
    protocol: TCP
    nodePort: 32565
  type: NodePort

