apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- sealed-secret.yaml
- namespace.yaml
- service.yaml

images:
- name: listas-api
  newName: brucorreia/listas-api
  newTag: 004f1ff7e8e2ffa50476c489cd15b67282b4211b
