apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- sealed-secret.yaml
- namespace.yaml
- service.yaml

images:
- name: listas-api
  newName: brucorreia/listas-api
  newTag: ac675563f894df9b199600c28d0ef7b73cb5d331
