---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  namespace: minio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 10
            preference:
              matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - node03
          - weight: 30
            preference:
              matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - node02
          - weight: 50
            preference:
              matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - node01
          - weight: 100
            preference:
              matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - node04
      containers:
      - name: minio
        image: minio/minio:latest
        envFrom:
          - secretRef:
              name: minio-secrets
        ports:
          - containerPort: 9000
        volumeMounts:
          - mountPath: /data
            name: minio-storage
        command: ["server", "/data"]
      volumes:
        - name: minio-storage
          hostPath:
            path: /mnt/storage/minio
            type: DirectoryOrCreate